name: feroo_store
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.4.4


dependencies:
  flutter:
    sdk: flutter
  #core
  flutter_dotenv: ^5.2.1
  flutter_screenutil: ^5.9.3
  connectivity_plus: ^6.1.2
  flutter_native_splash: ^2.4.4


  cupertino_icons: ^1.0.8
  #FireBase
  firebase_core: ^3.10.0
  flutter_localization: ^0.3.1
  animate_do: ^3.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.jpg"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/play_store_512.png"

  very_good_analysis: ^7.0.0


  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env.dev
    - .env.prod
    - assets/images/
    - assets/svg/
    - lang/ar.json
    - lang/en.json


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  #Arabic Font
     - family: cairo
       fonts:
         - asset: assets\fonts\arabic\cairo\Cairo-Bold.ttf
           weight: 700
         - asset: assets\fonts\arabic\cairo\Cairo-Medium.ttf
           weight: 500
         - asset: assets\fonts\arabic\cairo\Cairo-Regular.ttf
           weight: 400
    #English Font
     - family: poppins
       fonts:
         - asset: assets\fonts\english\poppins\Poppins-Bold.ttf
           weight: 700
         - asset: assets\fonts\english\poppins\Poppins-Medium.ttf
           weight: 500
         - asset: assets\fonts\english\poppins\Poppins-Regular.ttf
           weight: 400
